name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BASEURL: ${{ secrets.BASEURL }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Testing
    defaults:
      run:
        working-directory: ./framework

    steps:
      - uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Test
      run: |
         npm install
         npm run lint
         npm run test
